[tool.poetry]
name = "langgraph_framework"
version = "0.1.0"
description = ""
authors = ["viktor-vilskyi <viktor@terrificlive.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
langgraph = "^1.2.11"
langchain-openai = "^1.6.2"
python-dotenv = "^1.2.3"
langfuse = "^4.15.4"
langchain = "^1.4.2"
langchain-core = "^1.6.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
