[tool.poetry]
name = "ai-agents"
version = "0.1.0"
description = ""
authors = ["viktor-vilskyi <viktor@terrificlive.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
huggingface-hub = "^1.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
